### ISSUE TITLE
Throttling

### ISSUE THREAD

**Issue by LudwikZimmenhof** [SmellyN3rd/instaling-solver#1]
Hi, could you do a throttle option to do sleep(x) beetwen making words?

**Comment by SmellyN3rd** [comment]
Hello and thanks for Your feedback. I've added the `--delay` option to throttle the answer speed as you suggested.

**Comment by LudwikZimmenhof** [comment]
thank

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
